### ISSUE TITLE
Fix on file save/change

### ISSUE THREAD

**Issue by Lippiece** [rich-newman/typescript-analyzer-eslint-prettier#1]
Hi. Thanks for the extension. 

Is there any way to apply all the fixes on file save/change?

**Comment by rich-newman** [comment]
At present this is not implemented.  

This was due to personal conviction that it would be better to be able to control prettier reformatting rather than having it happen automatically.  However, having used the extension myself for a bit I can see this is a desirable feature and will add it in a future release.

**Comment by rich-newman** [comment]
This has now been implemented.  

If you have version 2.4 then there's an option on Tools/Options/TypeScript Analyzer (ESLint) to turn it on, called 'Fix and format on Save', second from the top of the dialog.  If you set that to 'True' then it will fix when a file is saved.
