### ISSUE TITLE
Failed to load plugin 'prettier'

### ISSUE THREAD

**Issue by daze99** [rich-newman/typescript-analyzer-eslint-prettier#2]
Since updating to Visual Studio version 17.3.4 I get the following error when the extension is initialized:

**Failed to load plugin 'prettier' declared in 'PersonalConfig#overrides[0]': Cannot find module 'eslint-plugin-prettier'**

I already uninstalled and reinstalled the extension. (I also removed the _TypeScriptAnalyzerConfig_ folder in my user profile)

**Comment by rich-newman** [comment]
I don't see this issue.  I have 17.3.4 installed and the extension is working fine for me.

This error happens if you have a local node_modules in your project with eslint installed but not prettier, although this may not be your specific problem.  Try Tools/Options/Enable local node_modules and set it to False, which forces the Analyzer to use its own install, which has prettier obviously.

**Comment by daze99** [comment]
Disabling local _node_modules_ solved the issue.
